### ISSUE TITLE
出现编码问题怎么办

### ISSUE THREAD

**Issue by QCEEE** [Aabyss-Team/ARL#5]
使用URL创建项目时无法开始，显示error
日志文件报错如下：
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/opt/ARL/app/tasks/domain.py", line 1085, in domain_task
    d.run()
  File "/opt/ARL/app/tasks/domain.py", line 1060, in run
    self.domain_fetch()
  File "/opt/ARL/app/tasks/domain.py", line 827, in domain_fetch
    self.domain_brute()
  File "/opt/ARL/app/tasks/domain.py", line 537, in domain_brute
    wildcard_domain_ip=self.not_found_domain_ips)
  File "/opt/ARL/app/tasks/domain.py", line 382, in domain_brute
    b = DomainBrute(base_domain, word_file, wildcard_domain_ip)
  File "/opt/ARL/app/tasks/domain.py", line 32, in __init__
    self.dicts = utils.load_file(word_file)
  File "/opt/ARL/app/utils/__init__.py", line 32, in load_file
    return f.readlines()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by AabyssZG** [comment]
根据具体报错，在 `.py` 文件第一行加上 `# -*- coding:utf-8 -*-` 试试看

**Comment by QCEEE** [comment]
我改了，但是依旧存在报错的问题

**Comment by QCEEE** [comment]
我之前修改过我的字典文件，我查看报错显示文件存在编码问题，我重新编码之后问题解决了，谢谢

**Comment by AabyssZG** [comment]
好的，我也有猜测字典文件的问题，解决就好
